/* mfrc522.c - simple MFRC522 HAL SPI driver for STM32 (CS=PA4, RST=PB12)
   Works with mfrc522.h provided earlier.
*/

#include "mfrc522.h"
#include "stm32f3xx_hal.h"
#include <string.h>

/* SPI handle declared in main.c generated by CubeMX */
extern SPI_HandleTypeDef hspi1;

/* Helper macros for CS */
static inline void MFRC522_Select(void) {
    HAL_GPIO_WritePin(MFRC522_CS_PORT, MFRC522_CS_PIN, GPIO_PIN_RESET);
}
static inline void MFRC522_Unselect(void) {
    HAL_GPIO_WritePin(MFRC522_CS_PORT, MFRC522_CS_PIN, GPIO_PIN_SET);
}

/* Low level write and read register via SPI */
void MFRC522_WriteRegister(uint8_t reg, uint8_t value)
{
    uint8_t addr = ((reg << 1) & 0x7E); // write -> MSB=0
    uint8_t tx[2] = { addr, value };
    MFRC522_Select();
    HAL_SPI_Transmit(&hspi1, tx, 2, HAL_MAX_DELAY);
    MFRC522_Unselect();
}

uint8_t MFRC522_ReadRegister(uint8_t reg)
{
    uint8_t addr = ((reg << 1) & 0x7E) | 0x80; // read -> set MSB=1
    uint8_t tx = addr;
    uint8_t rx = 0;
    MFRC522_Select();
    HAL_SPI_Transmit(&hspi1, &tx, 1, HAL_MAX_DELAY);
    HAL_SPI_Receive(&hspi1, &rx, 1, HAL_MAX_DELAY);
    MFRC522_Unselect();
    return rx;
}

/* Set/Clear bits in register */
void MFRC522_SetBitMask(uint8_t reg, uint8_t mask)
{
    uint8_t tmp = MFRC522_ReadRegister(reg);
    MFRC522_WriteRegister(reg, tmp | mask);
}

void MFRC522_ClearBitMask(uint8_t reg, uint8_t mask)
{
    uint8_t tmp = MFRC522_ReadRegister(reg);
    MFRC522_WriteRegister(reg, tmp & (~mask));
}

/* Soft reset */
void MFRC522_Reset(void)
{
    MFRC522_WriteRegister(CommandReg, PCD_RESETPHASE);
    HAL_Delay(50);
}

/* Turn on/off antenna */
void MFRC522_AntennaOn(void)
{
    uint8_t value = MFRC522_ReadRegister(TxControlReg);
    if (!(value & 0x03)) {
        MFRC522_SetBitMask(TxControlReg, 0x03);
    }
}

void MFRC522_AntennaOff(void)
{
    MFRC522_ClearBitMask(TxControlReg, 0x03);
}

/* Internal: calculate CRC using MFRC522 hardware */
static void MFRC522_CalculateCRC(uint8_t *data, uint8_t len, uint8_t *result)
{
    MFRC522_WriteRegister(CommandReg, PCD_IDLE);
    MFRC522_WriteRegister(DivIrqReg, 0x04);          // Clear CRCIRq
    MFRC522_SetBitMask(FIFOLevelReg, 0x80);          // Clear FIFO pointer

    // write data to FIFO
    for (uint8_t i = 0; i < len; i++) {
        MFRC522_WriteRegister(FIFODataReg, data[i]);
    }
    MFRC522_WriteRegister(CommandReg, PCD_CALCCRC);

    // wait for CRC calculation
    uint16_t i = 5000;
    uint8_t n;
    do {
        n = MFRC522_ReadRegister(DivIrqReg);
        i--;
    } while (i && !(n & 0x04));

    // Read CRC result
    result[0] = MFRC522_ReadRegister(CRCResultRegL);
    result[1] = MFRC522_ReadRegister(CRCResultRegM);
}

/* High level Init */
void MFRC522_Init(void)
{
    // Ensure CS is high (unselected)
    MFRC522_Unselect();

    // Reset by toggling RST pin (user should ensure RST pin is configured)
    HAL_GPIO_WritePin(MFRC522_RST_PORT, MFRC522_RST_PIN, GPIO_PIN_SET);
    HAL_Delay(50);

    MFRC522_Reset();
    HAL_Delay(50);

    MFRC522_WriteRegister(TModeReg, 0x8D);     // Timer: TPrescaler*Reload
    MFRC522_WriteRegister(TPrescalerReg, 0x3E);
    MFRC522_WriteRegister(TReloadRegL, 30);
    MFRC522_WriteRegister(TReloadRegH, 0);

    MFRC522_WriteRegister(TxASKReg, 0x40);     // 100%ASK
    MFRC522_WriteRegister(ModeReg, 0x3D);      // CRC initial value 0x6363

    MFRC522_AntennaOn();
}

/* Send command to card and receive response */
uint8_t MFRC522_ToCard(uint8_t command, uint8_t *sendData, uint8_t sendLen,
                       uint8_t *backData, uint16_t *backLen)
{
    uint8_t status = MI_ERR;
    uint8_t irqEn = 0x00;
    uint8_t waitIRq = 0x00;
    uint8_t lastBits;
    uint8_t n;
    uint16_t i;

    if (command == PCD_AUTHENT) {
        irqEn = 0x12;
        waitIRq = 0x10;
    } else if (command == PCD_TRANSCEIVE) {
        irqEn = 0x77;
        waitIRq = 0x30;
    }

    MFRC522_WriteRegister(CommIEnReg, irqEn | 0x80); // enable interrupt request
    MFRC522_ClearBitMask(CommIrqReg, 0x80); // clear all interrupt request bits
    MFRC522_SetBitMask(FIFOLevelReg, 0x80); // flush FIFO

    // Write data to FIFO
    for (i = 0; i < sendLen; i++) {
        MFRC522_WriteRegister(FIFODataReg, sendData[i]);
    }

    MFRC522_WriteRegister(CommandReg, PCD_IDLE);
    MFRC522_SetBitMask(BitFramingReg, 0x80); // start transmission

    MFRC522_WriteRegister(CommandReg, command);
    if (command == PCD_TRANSCEIVE) {
        MFRC522_SetBitMask(BitFramingReg, 0x80); // StartSend=1, transmission of data starts
    }

    // Wait for the command to complete.
    i = 2000; // approx timeout
    do {
        n = MFRC522_ReadRegister(CommIrqReg);
        i--;
    } while (i && !(n & 0x01) && !(n & waitIRq));

    MFRC522_ClearBitMask(BitFramingReg, 0x80);

    if (i != 0) {
        uint8_t errorReg = MFRC522_ReadRegister(ErrorReg);
        if (!(errorReg & 0x1B)) {
            status = MI_OK;
            if (n & irqEn & 0x01) {
                status = MI_NOTAGERR;
            }

            if (command == PCD_TRANSCEIVE) {
                n = MFRC522_ReadRegister(FIFOLevelReg);
                lastBits = MFRC522_ReadRegister(ControlReg) & 0x07;
                if (lastBits) {
                    *backLen = (n - 1) * 8 + lastBits;
                } else {
                    *backLen = n * 8;
                }

                if (n == 0) n = 1;
                if (n > 16) n = 16;

                // Read the received data from FIFO
                for (uint8_t idx = 0; idx < n; idx++) {
                    backData[idx] = MFRC522_ReadRegister(FIFODataReg);
                }
            }
        } else {
            status = MI_ERR;
        }
    }

    return status;
}

/* Request: detect card in range */
uint8_t MFRC522_Request(uint8_t reqMode, uint8_t *TagType)
{
    uint8_t status;
    uint16_t backBits; // the received data length (in bits)

    MFRC522_WriteRegister(BitFramingReg, 0x07); // TxLastBists = 7

    TagType[0] = reqMode;
    status = MFRC522_ToCard(PCD_TRANSCEIVE, TagType, 1, TagType, &backBits);

    if ((status != MI_OK) || (backBits != 0x10)) {
        status = MI_ERR;
    }

    return status;
}

/* Anti-collision: return 5 byte UID (serNum) */
uint8_t MFRC522_Anticoll(uint8_t *serNum)
{
    uint8_t status;
    uint8_t i;
    uint8_t serNumCheck = 0;
    uint16_t unLen;

    MFRC522_WriteRegister(BitFramingReg, 0x00); // TxLastBits = 0

    uint8_t buf[2];
    buf[0] = PICC_ANTICOLL;
    buf[1] = 0x20;
    status = MFRC522_ToCard(PCD_TRANSCEIVE, buf, 2, serNum, &unLen);

    if (status == MI_OK) {
        // serNum should contain 5 bytes
        for (i = 0; i < 4; i++) {
            serNumCheck ^= serNum[i];
        }
        if (serNumCheck != serNum[4]) {
            status = MI_ERR;
        }
    }
    return status;
}

/* Select the scanned tag (optional, used for authentication) */
uint8_t MFRC522_SelectTag(uint8_t *serNum)
{
    uint8_t i;
    uint8_t buf[9];
    uint8_t size;
    uint8_t status;
    uint16_t recvBits;

    buf[0] = PICC_SElECTTAG;
    buf[1] = 0x70;
    for (i = 0; i < 5; i++) {
        buf[i + 2] = serNum[i];
    }

    // Calculate CRC
    uint8_t crc[2];
    MFRC522_CalculateCRC(buf, 7, crc);
    buf[7] = crc[0];
    buf[8] = crc[1];

    status = MFRC522_ToCard(PCD_TRANSCEIVE, buf, 9, buf, &recvBits);
    if ((status == MI_OK) && (recvBits == 0x18)) {
        size = buf[0];
        return size;
    } else {
        return 0;
    }
}

/* Halt card */
void MFRC522_Halt(void)
{
    uint8_t buff[4];
    buff[0] = PICC_HALT;
    buff[1] = 0;
    uint8_t crc[2];
    MFRC522_CalculateCRC(buff, 2, crc);
    buff[2] = crc[0];
    buff[3] = crc[1];

    (void)MFRC522_ToCard(PCD_TRANSCEIVE, buff, 4, buff, NULL);
}

/* Convenience: Check for a card and return UID (5 bytes) */
uint8_t MFRC522_Check(uint8_t *id)
{
    uint8_t status;
    uint8_t tagtype[2];
    status = MFRC522_Request(PICC_REQIDL, tagtype);
    if (status != MI_OK) {
        return MI_NOTAGERR;
    }

    status = MFRC522_Anticoll(id);
    if (status != MI_OK) {
        return MI_ERR;
    }

    // select tag (optional)
    MFRC522_SelectTag(id);
    MFRC522_Halt();

    return MI_OK;
}
